name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential checkinstall libssl-dev
      - run: sudo apt-get install -y expect

      - name: Install Dependencies
          run: npm ci --prefix web

      - name: Build
          if: success()
          run: |
            npm run build.back4app --prefix web

      - run: chmod +x ./.github/scripts/deploy.sh
      - run: chmod +x ./.github/scripts/script.exp
      - name: push to back4app
        run: ./.github/scripts/script.exp
