name: Build

on:
  push:
    branches:
      - feature/pipeline
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
#      - run: curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
#      - run: sudo apt-get update
#      - run: sudo apt-get install -y build-essential checkinstall libssl-dev
      - run: sudo apt-get install -y expect
#      - run: sudo apt-get install npm
#      - run: sudo npm install
      - run: expect ./.github/scripts/script.exp