name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --prefix web

      - name: Build
        if: success()
        run: |
          npm run prebuild --prefix web
          npm run build.back4app --prefix web

      - name: Install Back4App CLI
        if: success()
        run: curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash

      - name: Install expect
        if: success()
        run: sudo apt-get install -y expect

      - name: Replace B4A_ACCOUNT_KEY
        if: success()
        run: find script.exp -type f -exec sed -i ''s/#{B4A_ACCOUNT_KEY}#/${{ secrets.B4A_ACCOUNT_KEY }}/g'' {} \;

      - name: File Permissions
        if: success()
        run: |
          chmod +x ./deploy.sh
          chmod +x ./script.exp

      - name: Deploy to Back4App
        if: success()
        run: expect script.exp
