name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential checkinstall libssl-dev
      - run: sudo apt-get install -y expect

      #      - name: Install Dependencies
      #        run: npm ci --prefix web
      #
      #      - name: Build
      #        if: success()
      #        run: |
      #          npm run build.back4app --prefix web

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "$B4A_ACCOUNT_KEY"
          replace: "${{ secrets.B4A_ACCOUNT_KEY }}"
          include: "script.exp"
      - run: chmod +x ./deploy.sh
      - run: chmod +x ./script.exp
      - run: ls
      - name: push to back4app
        run: expect script.exp
