name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential checkinstall libssl-dev
      - run: sudo apt-get install -y expect
      - run: sudo apt-get install npm
      - name: install npm
        run: |
          cd ./web
          sudo npm install
      - run: sudo npm i -g @angular/cli
      - name: build ng app
        run: |
          cd ./web
          ng build --output-path=../public
      - run: chmod +x ./.github/scripts/deploy.sh
      - run: chmod +x ./.github/scripts/script.exp
      - run: ./.github/scripts/script.exp