name: Build

on:
  push:
    branches:
      - feature/pipeline
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      - run: curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
#      - run: sudo apt-get update
#      - run: sudo apt-get install -y build-essential checkinstall libssl-dev
      - run: sudo apt-get install -y expect
#      - run: sudo apt-get install npm
#      - run: sudo npm install
      - run: ls -all $PWD
      - name: test expect script
        working-directory: scripts
        run: |
          expect scripts/script.exp
